In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Data_for_UCI_grid_stability.csv')
df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4      stab     stabf  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1    -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable  
...        ...       ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  0.023892  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120 -0.025803    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984 -0.031810    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  0.037789  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  0.045263  unstable  

[10000 rows x 14 columns]

In [3]:
df = df.drop(columns='stab', axis=1)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stabf   10000 non-null  object 
dtypes: float64(12), object(1)
memory usage: 1015.8+ KB


In [5]:
df.duplicated().sum()

0

In [6]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [7]:
df.shape

(10000, 13)

In [8]:
df['stabf'].describe()

count        10000
unique           2
top       unstable
freq          6380
Name: stabf, dtype: object

In [9]:
df['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [10]:
X = df.drop(columns='stabf')
y = df['stabf']

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)
y = pd.DataFrame(y, columns=['stabf'])

In [12]:
y

stabf
0         1
1         0
2         1
3         1
4         1
...     ...
9995      1
9996      0
9997      0
9998      1
9999      1

[10000 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
y_train.value_counts()

stabf
1        5092
0        2908
dtype: int64

In [14]:
df.columns

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4', 'stabf'],
      dtype='object')

In [15]:
# import imblearn
# from imblearn.over_sampling import SMOTE
# smote = SMOTE(random_state=1)
# x_train_balanced, y_balanced = smote.fit_resample(x_train, y_train)

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
normalised_train_df = scaler.fit_transform(x_train)
normalised_train_df = pd.DataFrame(normalised_train_df, columns=x_train.columns)
normalised_train_df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     0.367327 -0.986042  0.650447  1.547527 -0.291490  0.061535  1.293862   
1    -0.064659  0.089437  1.035079 -1.641494  0.619865 -0.067235 -1.502925   
2    -1.467850  1.298418 -0.502536  1.166046 -0.180521  0.490603  0.682560   
3     0.820081  0.529920  1.299657 -1.141975 -0.812854 -0.763632  1.521579   
4     0.665424 -1.425627  0.312300  0.919137 -1.614296  0.760315  1.422019   
...        ...       ...       ...       ...       ...       ...       ...   
7995  1.551314  0.007408 -1.177640  1.016898 -0.397177  0.759820 -0.636951   
7996  1.015925 -0.223483 -1.489381 -1.479078  0.451468 -0.731994  0.990355   
7997  0.657609 -0.722756 -1.405888 -0.274301 -0.012584  1.438694 -0.364266   
7998 -0.059316 -1.260532 -1.010471 -0.877808 -0.779769  0.828824  0.516923   
7999 -1.473214  0.638438  0.250122 -0.996484  1.950944 -1.163800 -0.732842   

            p4        g1        g2        g3        g4  
0    -0.845074  0.160918  0.339859  0.585568  0.492239  
1     0.486613 -0.293143 -1.558488  1.429649 -1.443521  
2    -0.855302  1.399350  1.451534 -1.045743  0.492489  
3     0.658780 -0.958319  1.361958  1.604140  0.275303  
4     0.639243  1.676895  0.695660  1.137504 -1.312575  
...        ...       ...       ...       ...       ...  
7995  0.572703 -1.209413  0.313976 -1.625728 -0.637401  
7996 -1.048148 -1.094647 -0.755209  0.734821 -0.304433  
7997 -1.046683  1.253539  0.293100 -1.550587  0.810344  
7998  0.018984 -0.182448 -0.388255 -0.726781  1.667916  
7999 -1.513302  1.230438 -1.174110  1.179282  0.783627  

[8000 rows x 12 columns]

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
normalised_test_df = scaler.fit_transform(x_test)
normalised_test_df = pd.DataFrame(normalised_test_df, columns=x_test.columns)
normalised_test_df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     0.592163 -0.420565  1.472472  1.093036  0.426786 -1.504594 -0.792677   
1     0.199183  0.364543 -0.190076 -0.518473 -0.229402 -1.071766  0.427103   
2    -1.086035 -0.321834 -0.873505  0.011761 -0.977094  0.094896  0.813041   
3    -0.087014 -1.113357  0.361518 -1.684316  0.792280 -1.649041  0.410662   
4     0.873004  1.425833  0.080476  1.681022 -0.154247 -0.024315 -0.197525   
...        ...       ...       ...       ...       ...       ...       ...   
1995  1.119526 -0.682371 -1.362900  1.261070  0.266377 -0.817583  0.745388   
1996 -1.084900 -0.815496  1.010385  0.326900 -0.167494  0.322284  1.002069   
1997  0.947138 -1.668313 -1.629077  0.518632 -1.576793  1.566742  0.094662   
1998 -1.127354  0.184573 -0.238207  0.409415 -1.205991  0.718553  0.029632   
1999 -1.385560  1.499043  0.272971  1.480274  0.682028 -1.498433 -0.789188   

            p4        g1        g2        g3        g4  
0     1.600201 -0.925703  1.175287 -1.492644  1.086291  
1     1.052337 -1.655910 -0.395949  1.412703  1.227535  
2     0.751381  1.450284 -1.444370  0.654216 -1.679799  
3    -0.084473  0.066085 -1.679450 -0.349573  1.057439  
4     0.485988  0.119716 -1.475773  0.957057 -0.817608  
...        ...       ...       ...       ...       ...  
1995 -0.370774  0.471600 -0.114316 -1.251379 -1.280864  
1996 -1.049289  0.941736  0.899379 -1.050349 -1.091915  
1997  0.997188 -1.261183  0.128899  0.576286  1.320848  
1998  1.293823  1.518021  0.800172 -1.348463 -0.799858  
1999  1.155547  0.479208 -0.920581  0.009039  1.190559  

[2000 rows x 12 columns]

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from xgboost.sklearn import XGBClassifier
from lightgbm import LGBMClassifier

In [19]:
rfc = RandomForestClassifier(random_state=1)
rfc.fit(normalised_train_df,y_train)

RandomForestClassifier(random_state=1)

In [20]:
rfc_predictions = rfc.predict(normalised_test_df)

In [21]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
cnf_mat = confusion_matrix(y_true=y_test, y_pred=rfc_predictions)

In [22]:
cnf_mat

array([[ 624,   88],
       [  56, 1232]], dtype=int64)

In [23]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(rfc, normalised_train_df, y_train, cv=5, scoring='f1_macro')
scores

array([0.91143756, 0.91136454, 0.91564855, 0.90214725, 0.91555674])


#### What is the accuracy on the test set using the random forest classifier? 
#### In 4 decimal places.

In [56]:
accuracy = accuracy_score(y_true=y_test, y_pred=rfc_predictions)
print('Accuracy: {}'.format((accuracy)))

#precision
precision = precision_score(y_true=y_test, y_pred=rfc_predictions)
print('Presicion: {}'.format(round(precision*100), 2))

#recall
recall = recall_score(y_true=y_test, y_pred=rfc_predictions)
print('Recall: {}'.format(round(recall*100), 2))

f1 = f1_score(y_true=y_test, y_pred=rfc_predictions)
print('F1: {}'.format(round(f1*100), 2)) 

Accuracy: 0.928
Presicion: 93
Recall: 96
F1: 94


In [28]:
#pip install lightgbm

In [29]:
xtc = ExtraTreesClassifier(random_state=1)
xtc.fit(normalised_train_df,y_train)

ExtraTreesClassifier(random_state=1)

In [30]:
xtc_predictions = xtc.predict(normalised_test_df)

cnf_mat = confusion_matrix(y_true=y_test, y_pred=xtc_predictions)

cnf_mat

array([[ 602,  110],
       [  38, 1250]], dtype=int64)

In [31]:
scores = cross_val_score(xtc, normalised_train_df, y_train, cv=5, scoring='f1_macro')
scores

array([0.91104788, 0.90890596, 0.91695487, 0.91218763, 0.92433757])

In [32]:
accuracy = accuracy_score(y_true=y_test, y_pred=xtc_predictions)
print('Accuracy: {}'.format(round(accuracy, 4)))

#precision
precision = precision_score(y_true=y_test, y_pred=xtc_predictions)
print('Presicion: {}'.format(round(precision, 4)))

#recall
recall = recall_score(y_true=y_test, y_pred=xtc_predictions)
print('Recall: {}'.format(round(recall,4)))

f1 = f1_score(y_true=y_test, y_pred=xtc_predictions)
print('F1: {}'.format(round(f1,4)))

Accuracy: 0.926
Presicion: 0.9191
Recall: 0.9705
F1: 0.9441


In [33]:
xgb = XGBClassifier(random_state=1)
xgb.fit(normalised_train_df,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=1, ...)

In [34]:
xgb_predictions = xgb.predict(normalised_test_df)

cnf_mat = confusion_matrix(y_true=y_test, y_pred=xgb_predictions)

cnf_mat

array([[ 647,   65],
       [  43, 1245]], dtype=int64)

In [35]:
scores = cross_val_score(xgb, normalised_train_df, y_train, cv=5, scoring='f1_macro')
scores

array([0.9366625 , 0.94470459, 0.93293748, 0.93646215, 0.94718274])


#### What is the accuracy on the test set using the XGboost classifier? 
#### In 4 decimal places.

In [36]:
accuracy = accuracy_score(y_true=y_test, y_pred=xgb_predictions)
print('Accuracy: {}'.format(round(accuracy,4)))

#precision
precision = precision_score(y_true=y_test, y_pred=xgb_predictions)
print('Presicion: {}'.format(round(precision,4)))

#recall
recall = recall_score(y_true=y_test, y_pred=xgb_predictions)
print('Recall: {}'.format(round(recall, 4)))

f1 = f1_score(y_true=y_test, y_pred=xgb_predictions)
print('F1: {}'.format(round(f1, 4)))

Accuracy: 0.946
Presicion: 0.9504
Recall: 0.9666
F1: 0.9584


In [37]:
lgbm = LGBMClassifier(random_state=1)
lgbm.fit(normalised_train_df,y_train)

LGBMClassifier(random_state=1)

In [38]:
lgbm_predictions = lgbm.predict(normalised_test_df)

cnf_mat = confusion_matrix(y_true=y_test, y_pred=lgbm_predictions)

cnf_mat

array([[ 636,   76],
       [  51, 1237]], dtype=int64)

In [39]:
scores = cross_val_score(lgbm, normalised_train_df, y_train, cv=5, scoring='f1_macro')
scores

array([0.92843386, 0.94466058, 0.93147894, 0.92695545, 0.94360434])

#### What is the accuracy on the test set using the LGBM classifier? 
#### In 4 decimal places.

In [40]:
accuracy = accuracy_score(y_true=y_test, y_pred=lgbm_predictions)
print('Accuracy: {}'.format(round(accuracy,4)))

#precision
precision = precision_score(y_true=y_test, y_pred=lgbm_predictions)
print('Presicion: {}'.format(round(precision,4)))

#recall
recall = recall_score(y_true=y_test, y_pred=lgbm_predictions)
print('Recall: {}'.format(round(recall,4)))

f1 = f1_score(y_true=y_test, y_pred=lgbm_predictions)
print('F1: {}'.format(round(f1,4)))

Accuracy: 0.9365
Presicion: 0.9421
Recall: 0.9604
F1: 0.9512


#### Using the ExtraTreesClassifier as your estimator with cv=5, n_iter=10, scoring = 'accuracy', n_jobs = -1, verbose = 1 and random_state = 1. What are the best hyperparameters from the randomized search CV?

In [41]:
from sklearn.model_selection import RandomizedSearchCV
xt_clf = ExtraTreesClassifier(verbose=1,
                              random_state=1,
                              n_jobs=-1)

In [42]:
from random import randint
import numpy as np

parameters = {
    'n_estimators': np.arange(100,1000, 100),
    'min_samples_split' : [2,5,7],
    'min_samples_leaf' : [4,6,8],
    'max_features' : ['auto', 'sqrt', 'log2', None]
}

In [43]:
def hypertuning(xt_clf, parameters, n_iter, normalised_train_df, y_train):
    rdm_search = RandomizedSearchCV(xt_clf, parameters, n_jobs=-1, n_iter=n_iter, cv=5, verbose =1, random_state=1, scoring ='accuracy')
    rdm_search.fit(normalised_train_df, y_train)
    ht_param = rdm_search.best_params_
    ht_score = rdm_search.best_score_
    return ht_param, ht_score

In [44]:
xtc_param, xtc_ht_score = hypertuning(xtc, parameters, 10, normalised_train_df, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


In [45]:
xtc_param, xtc_ht_score

({'n_estimators': 500,
  'min_samples_split': 2,
  'min_samples_leaf': 4,
  'max_features': None},
 0.92675)

#### Train a new ExtraTreesClassifier Model with the new Hyperparameters from the RandomizedSearchCV (with random_state = 1). Is the accuracy of the new optimal model higher or lower than the initial ExtraTreesClassifier model with no hyperparameter tuning? 

In [46]:
xt_clf_new = ExtraTreesClassifier(n_estimators=500,min_samples_split= 2,min_samples_leaf= 4,max_features= None, random_state= 1)

In [47]:
xt_clf_new.fit(normalised_train_df, y_train)

ExtraTreesClassifier(max_features=None, min_samples_leaf=4, n_estimators=500,
                     random_state=1)

In [48]:
xt_clf_new_predictions = xt_clf_new.predict(normalised_test_df)

In [49]:
accuracy = accuracy_score(y_true=y_test, y_pred=xt_clf_new_predictions)
print('Accuracy: {}'.format((accuracy,4)))

Accuracy: (0.935, 4)


#### Feature importance using the optimal ExtraTreesClassifier model

In [54]:
feature_importance = pd.DataFrame(xt_clf_new.feature_importances_,
                                  index= normalised_train_df.columns,
                                  columns=['importance']).sort_values('importance', ascending=False)

In [55]:
feature_importance

importance
tau2    0.135056
tau1    0.133123
tau4    0.130239
tau3    0.130150
g3      0.111799
g4      0.108436
g2      0.107800
g1      0.102993
p3      0.010956
p2      0.010876
p4      0.010288
p1      0.008284